[workspace]
authors = [
    "Daniel San José Pro <42489409+danielsanjosepro@users.noreply.github.com>",
]
name = "franka_ros2_pixi"
version = "0.1.0"
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["scripts/set_ros_env.sh"]

[dependencies]
python = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
libcap = "*"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
jazzy = { features = ["jazzy", "dev", "extra"] }
jazzy-crisp = { features = ["jazzy", "dev", "extra", "crisp"] }
humble = { features = ["humble", "dev", "extra"] }
humble-crisp = { features = ["humble", "dev", "extra", "crisp"] }
kilted = { features = ["kilted", "dev", "extra"] }
kilted-crisp = { features = ["kilted", "dev", "extra", "crisp"] }

# feature.humble
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.7.0,<4"
poco = ">=1.14.2,<2"
ros-humble-ament-clang-format = "*"
ros-humble-desktop = "*"
ros-humble-joint-state-publisher = "*"
ros-humble-moveit-core = "*"
ros-humble-moveit-kinematics = "*"
ros-humble-moveit-planners-ompl = "*"
ros-humble-moveit-ros-move-group = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-rmw-zenoh-cpp = "*"
ros-humble-ros2-control = "*"
ros-humble-ros2-controllers = "*"
ros-humble-xacro = "*"
rosdep = "*"
ros-humble-generate-parameter-library = ">=0.3.9,<0.4"

[feature.humble.tasks]
clone = "git clone https://github.com/frankarobotics/franka_ros2.git -b humble src/franka_ros2 && git clone https://github.com/frankarobotics/franka_description.git src/franka_description && git clone --recurse-submodules https://github.com/frankarobotics/libfranka.git src/libfranka"
update-libfranka = "cd src/libfranka && git submodule update --init --recursive && cd ../../"
apply-patches = "bash scripts/apply_patches.sh"
ignore-gazebo = "touch src/franka_ros2/franka_gazebo/COLCON_IGNORE"
build = "colcon --log-base log_humble build --symlink-install --build-base build_humble --install-base install_humble --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev"
setup = { depends-on = [
    "clone",
    "update-libfranka",
    "apply-patches",
    "ignore-gazebo",
    "build",
] }
franka = "ros2 launch scripts/launch/franka.launch.py"

# jazzy
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.7.0,<4"
poco = ">=1.14.2,<2"
ros-jazzy-ament-clang-format = ">=0.17.2,<0.18"
ros-jazzy-desktop = "*"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-moveit-core = ">=2.12.3,<3"
ros-jazzy-moveit-kinematics = ">=2.12.3,<3"
ros-jazzy-moveit-planners-ompl = ">=2.12.3,<3"
ros-jazzy-moveit-ros-move-group = ">=2.12.3,<3"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-rmw-zenoh-cpp = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-control-cmake = ">=0.2.1,<0.3"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-xacro = ">=2.0.13,<3"
rosdep = "*"

[feature.jazzy.tasks]
clone = "git clone https://github.com/frankarobotics/franka_ros2.git -b jazzy src/franka_ros2 && git clone https://github.com/frankarobotics/franka_description.git src/franka_description && git clone --recurse-submodules https://github.com/frankarobotics/libfranka.git src/libfranka"
update-libfranka = "cd src/libfranka && git submodule update --init --recursive && cd ../../"
apply-patches = "bash scripts/apply_patches.sh"
ignore-gazebo = "touch src/franka_ros2/franka_gazebo/COLCON_IGNORE"
build = "colcon --log-base log_jazzy build --symlink-install --build-base build_jazzy --install-base install_jazzy --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev"
clone-crisp = "git clone https://github.com/utiasdsl/crisp_controllers.git src/crisp_controllers"
setup = { depends-on = [
    "clone",
    "update-libfranka",
    "apply-patches",
    "ignore-gazebo",
    "build",
] }
franka = "ros2 launch scripts/launch/franka.launch.py"

# kilted
[feature.kilted]
channels = [
    "https://prefix.dev/robostack-kilted",
    "https://fast.prefix.dev/conda-forge",
]

[feature.kilted.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.7.0,<4"
poco = ">=1.14.2,<2"
ros-kilted-ament-cmake = "*"
ros-kilted-generate-parameter-library = "*"
ros-kilted-ros-environment = "*"
ros-kilted-joint-state-publisher = "*"
ros-kilted-launch = "*"
ros-kilted-launch-ros = "*"
ros-kilted-moveit-core = "*"
ros-kilted-moveit-msgs = "*"
ros-kilted-rmw-cyclonedds-cpp = "*"
ros-kilted-robot-state-publisher = "*"
ros-kilted-ros2-control = "*"
ros-kilted-ros2-control-cmake = "*"
ros-kilted-ros2-controllers = "*"
ros-kilted-rosidl-default-generators = "*"
ros-kilted-ros2launch = "*"
ros-kilted-visualization-msgs = "*"
ros-kilted-xacro = "*"
rosdep = "*"

[feature.kilted.tasks]
clone = "git clone https://github.com/frankarobotics/franka_ros2.git -b jazzy src/franka_ros2 && git clone https://github.com/frankarobotics/franka_description.git src/franka_description && git clone --recurse-submodules https://github.com/frankarobotics/libfranka.git src/libfranka"
update-libfranka = "cd src/libfranka && git submodule update --init --recursive && cd ../../"
apply-patches = "bash scripts/apply_patches.sh"
ignore-gazebo = "touch src/franka_ros2/franka_gazebo/COLCON_IGNORE"
build = "colcon --log-base log_kilted build --symlink-install --build-base build_kilted --install-base install_kilted --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev"
setup = { depends-on = [
    "clone",
    "update-libfranka",
    "apply-patches",
    "ignore-gazebo",
    "build",
] }
franka = "ros2 launch scripts/launch/franka.launch.py"

[feature.crisp.tasks]
crisp-figure-eight = "python examples/crisp_figure_eight.py"
crisp-teleop = "python examples/crisp_teleop.py"

[feature.dev.pypi-dependencies]
ruff = "*"
bumpver = "*"
build = "*"
twine = "*"
pre-commit = "*"
pytest = "*"     # for testing

[feature.extra.pypi-dependencies]
rich = "*"       # For nice prints
matplotlib = "*" # to do some plots

[feature.crisp.pypi-dependencies]
crisp-python = ">=3.0.0,<4"
